### ISSUE TITLE
Tejas Ozarkar

### ISSUE THREAD

**Issue by tejozarkar** [engineering-stream-hackathon/challenge#10]
## My project details

```yaml
employee:
  name: Tejas OZARKAR
  githubUsername: Tejas-Ozarkar
project:
  appUrl: http://teensy.xyz (Alternate: http://teensy-client.s3-website.ap-south-1.amazonaws.com)
  documentationUrl: https://github.com/tej-oz/teensy-client/blob/master/README.md
  openApiUrl: http://teensyapi-env.eba-k2xfeapv.ap-south-1.elasticbeanstalk.com/swagger-ui.html
  repositories:
    -
      name: teensy-client
      githubUrl: https://github.com/tej-oz/teensy-client
      travisUrl: https://travis-ci.com/github/tej-oz/teensy-client
    - name: teensy-server
      githubUrl: https://github.com/tej-oz/teensy-server
      travisUrl: https://travis-ci.com/github/tej-oz/teensy-server
```

## Have you given admin access to [engineering-stream-bot](https://github.com/engineering-stream-bot) ?  

- [x] Yes
