### ISSUE TITLE
Vibhu Pandey

### ISSUE THREAD

**Issue by pandeyvibhu** [engineering-stream-hackathon/challenge#11]
## My project details

```yaml
employee:
  name: Vibhu PANDEY
  githubUsername: pandeyvibhu
project:
  appUrl: http://dashbook-env.eba-kdtzaurv.ap-south-1.elasticbeanstalk.com/
  documentationUrl: https://pandeyvibhu.github.io/socgen-engstream-dashbook-backend/
  repositories:
    - name: socgen-engstream-dashbook-backend
      githubUrl: https://github.com/pandeyvibhu/socgen-engstream-dashbook-backend
      travisUrl: https://travis-ci.org/github/pandeyvibhu/socgen-engstream-dashbook-backend
    - name: socgen-eng-stream-dashbook-ui
      githubUrl: https://github.com/pandeyvibhu/socgen-eng-stream-dashbook-ui/
      travisUrl: https://travis-ci.org/github/pandeyvibhu/socgen-eng-stream-dashbook-ui
```

## Have you given admin access to [engineering-stream-bot](https://github.com/engineering-stream-bot) ?  

- [X] Yes
