### ISSUE TITLE
Avinasha Venkappa

### ISSUE THREAD

**Issue by Avinash1604** [engineering-stream-hackathon/challenge#13]
## My project details

```yaml
employee:
  name: Avinasha Venkappa
  githubUsername: Avinash1604
project:
  appUrl: https://avinash1604.github.io/bookmarks/home
  documentationUrl: https://github.com/Avinash1604/bookmarks/blob/master/README.md
  openApiUrl: https://bookmarks-tiny.herokuapp.com/swagger-ui.html
  monitoringUrl: 
  repositories:
    -
      name: bookmarks
      githubUrl: https://github.com/Avinash1604/bookmarks
      travisUrl: https://travis-ci.com/github/Avinash1604/bookmarks
      codacyUrl: https://app.codacy.com/manual/Avinash1604/bookmarks/dashboard
      coverageUrl: https://coveralls.io/github/Avinash1604/bookmarks
```

## Have you given admin access to [engineering-stream-bot](https://github.com/engineering-stream-bot) ?  

- [x] Yes

> :pushpin: **Note:** [Details about how to submit](https://engineering-stream-hackathon.github.io/challenge/#/?id=how-to-submit)
