### ISSUE TITLE
Navin Kumar

### ISSUE THREAD

**Issue by navinkumar0705** [engineering-stream-hackathon/challenge#14]
## My project details

```yaml
employee:
  name: Navin Kumar
  githubUsername: navinkumar0705
project:
  appUrl: 
  documentationUrl: https://github.com/navinkumar0705/urlzipper/blob/master/README.md
  openApiUrl: https://github.com/navinkumar0705/urlzipper/blob/master/swagger.json
  monitoringUrl: 
  repositories:
    -
      name: urlzipper
      githubUrl: https://github.com/navinkumar0705/urlzipper
      travisUrl: https://travis-ci.com/github/navinkumar0705/urlzipper
      codacyUrl: 
      coverageUrl: https://codecov.io/gh/navinkumar0705/urlzipper
    
```

## Have you given admin access to [engineering-stream-bot](https://github.com/engineering-stream-bot) ?  

- [x] Yes

> :pushpin: **Note:** [Details about how to submit](https://engineering-stream-hackathon.github.io/challenge/#/?id=how-to-submit)
