### ISSUE TITLE
Nupur Chatterjee

### ISSUE THREAD

**Issue by nupurc** [engineering-stream-hackathon/challenge#15]
## My project details

```yaml
employee:
  name: nupur chatterjee
  githubUsername: nupurc
project:
  appUrl: https://cardlibstorage.z13.web.core.windows.net/
  documentationUrl: https://engineering-stream-hackathon.github.io/challenge/
  openApiUrl: https://cardlibraryweb20200918102133-apim.azure-api.net/
  monitoringUrl: https://cloud.com/kibana
  repositories:
    -
      name: CardLibrary
      githubUrl: https://github.com/mycardlib/cardlib
      travisUrl: https://github.com/nupurc/CardLibrary/blob/master/.github/workflows/master_cardlib.yml
      codacyUrl: https://app.codacy.com/manual/nupurc/CardLibrary/dashboard
      coverageUrl: https://codecov.io/gh/nupurc/CardLibrary

```

## Have you given admin access to [engineering-stream-bot](https://github.com/engineering-stream-bot) ?  

- [x] Yes

> :pushpin: **Note:** [Details about how to submit](https://engineering-stream-hackathon.github.io/challenge/#/?id=how-to-submit)
