### ISSUE TITLE
Emmanuel Xavier

### ISSUE THREAD

**Issue by emmanuelxavier040** [engineering-stream-hackathon/challenge#16]
## My project details

```yaml
employee:
  name: Emmanuel XAVIER
  githubUsername: emmanuelxavier040
project:
  appUrl: https://bookyweb.herokuapp.com
  documentationUrl: https://emmanuelxavier040.github.io/booky-pages/
  openApiUrl: https://booky2020.herokuapp.com/swagger-ui.html
  repositories:
    - name: booky-web
      githubUrl: https://github.com/emmanuelxavier040/booky-web
      travisUrl: https://travis-ci.com/github/emmanuelxavier040/booky-web
    - name: booky-service
      githubUrl: https://github.com/emmanuelxavier040/booky-service
      travisUrl: https://travis-ci.com/github/emmanuelxavier040/booky-service
```

## Have you given admin access to [engineering-stream-bot](https://github.com/engineering-stream-bot) ?  

- [Yes] Yes

> :pushpin: **Note:** [Details about how to submit](https://engineering-stream-hackathon.github.io/challenge/#/?id=how-to-submit)
