### ISSUE TITLE
Amit Naik

### ISSUE THREAD

**Issue by Amitpnk** [engineering-stream-hackathon/challenge#18]
## My project details

```yaml
employee:
  name: Amit Naik
  githubUsername: Amitpnk
project:
  appUrl: https://bookmark-dashboard.web.app/
  documentationUrl: https://es-hackathon.github.io/documentation/#/
  openApiUrl: https://bookmarkwebapi20200916112033.azurewebsites.net/OpenAPI/index.html
  monitoringUrl: https://bookmarkweb20200916110752.azurewebsites.net/healthcheck-ui
  repositories:
    -
      name: bookmark-dashboard-api
      githubUrl: https://github.com/es-hackathon/bookmark-dashboard-api
      .NETCoreUrl: https://github.com/es-hackathon/bookmark-dashboard-api/actions?query=workflow%3A%22.NET+Core%22
      codacyUrl: https://app.codacy.com/gh/es-hackathon/bookmark-dashboard-api/dashboard
    - 
      name: bookmark-dashboard-ui
      githubUrl: https://github.com/es-hackathon/bookmark-dashboard-ui
      circleUrl: https://app.circleci.com/pipelines/github/es-hackathon/bookmark-dashboard-ui
      codacyUrl: https://app.codacy.com/gh/es-hackathon/bookmark-dashboard-ui/dashboard
    - 
      name: bookmark-dashboard-widget
      githubUrl: https://github.com/es-hackathon/bookmark-dashboard-widget
      circleUrl: https://app.circleci.com/pipelines/github/es-hackathon/bookmark-dashboard-widget
      codacyUrl: https://app.codacy.com/gh/es-hackathon/bookmark-dashboard-widget/dashboard
```

## Have you given admin access to [engineering-stream-bot](https://github.com/engineering-stream-bot) ?  

- [x] Yes

> :pushpin: **Note:** [Details about how to submit](https://engineering-stream-hackathon.github.io/challenge/#/?id=how-to-submit)
