### ISSUE TITLE
Akshya Chettiar 

### ISSUE THREAD

**Issue by AKSHYA1997** [engineering-stream-hackathon/challenge#19]
## My project details

```yaml
employee:
  name: Akshya CHETTIAR
  githubUsername: AKSHYA1997
project:
  appUrl: https://thoven-ui.herokuapp.com/login
  documentationUrl: https://akshya-engineering-stream-2020.github.io/thoven-docsify/#/
  openApiUrl: https://thoven-api.herokuapp.com/swagger-ui.html
  monitoringUrl: None
  repositories:
    -
      name: thoven-api
      githubUrl: https://github.com/akshya-engineering-stream-2020/thoven-api
      travisUrl: https://travis-ci.org/github/akshya-engineering-stream-2020/thoven-api
      codacyUrl: https://app.codacy.com/gh/akshya-engineering-stream-2020/thoven-api/dashboard
      coverageUrl: https://codecov.io/gh/akshya-engineering-stream-2020/thoven-api
    -
      name: thoven-ui
      githubUrl: https://github.com/akshya-engineering-stream-2020/thoven-ui
      travisUrl: https://travis-ci.org/github/akshya-engineering-stream-2020/thoven-ui
      codacyUrl: https://app.codacy.com/gh/akshya-engineering-stream-2020/thoven-ui/dashboard
      coverageUrl: https://codecov.io/gh/akshya-engineering-stream-2020/thoven-ui
```

## Have you given admin access to [engineering-stream-bot](https://github.com/engineering-stream-bot) ?  

- [x] Yes

> :pushpin: **Note:** [Details about how to submit](https://engineering-stream-hackathon.github.io/challenge/#/?id=how-to-submit)
