### ISSUE TITLE
Rakesh Venkataraman 

### ISSUE THREAD

**Issue by rakeshven** [engineering-stream-hackathon/challenge#20]
## My project details

```yaml
employee:
  name: Rakesh Venkataraman
  githubUsername: rakesh8693
project:
  appUrl: http://bma-env-1.eba-wgdegdsk.us-east-1.elasticbeanstalk.com/swagger-ui/index.html?configUrl=/BMA-docs/swagger-config
  documentationUrl: https://rakesh8693.github.io/bma-docs/#/?id=bookmark-and-url-shortening-application
  openApiUrl: http://bma-env-1.eba-wgdegdsk.us-east-1.elasticbeanstalk.com/swagger-ui/index.html?configUrl=/BMA-docs/swagger-config
  monitoringUrl: <Todo>
  repositories:
    -
      name: BookMark Management Application (bma-app-frontend)
      githubUrl: https://github.com/rakesh8693/bma-app-frontend
      travisUrl: https://travis-ci.com/github/rakesh8693/bma-app-frontend
	  
    - name: BookMark Management Application (bma-app-backend)
      githubUrl: https://github.com/rakesh8693/bma-app-backend
      travisUrl: https://travis-ci.com/github/rakesh8693/bma-app-backend
      codacyUrl: https://app.codacy.com/gh/rakesh8693/bma-app-backend/dashboard
      coverageUrl: https://codecov.io/gh/rakesh8693/bma-app-backend
```

## Have you given admin access to [engineering-stream-bot](https://github.com/engineering-stream-bot) ?  

- [x] Yes

> :pushpin: **Note:** [Details about how to submit](https://engineering-stream-hackathon.github.io/challenge/#/?id=how-to-submit)
