### ISSUE TITLE
Rajkumar ANGARE

### ISSUE THREAD

**Issue by rajangare** [engineering-stream-hackathon/challenge#21]
## My project details

```yaml
employee:
  name: Rajkumar ANGARE
  githubUsername: rajangare
project:
  appUrl: https://devs-from-matrix.github.io/ff4j-web-console/features
  documentationUrl: https://engineering-stream-hackathon.github.io/challenge/
  openApiUrl: http://localhost:8090/swagger-ui.html, http://localhost:8761, http://localhost:8888
  monitoringUrl: https://cloud.com/kibana
  repositories:
    -
      name: ff4j-spring-boot-starter-parent
      githubUrl: https://github.com/rajangare/app-discovery-service, https://github.com/rajangare/app-config-server, https://github.com/rajangare/app-config-repo, https://github.com/rajangare/bookmark-services, https://github.com/rajangare/bookmark-card-ui
      travisUrl: https://travis-ci.com/github/rajangare/bookmark-services
      codacyUrl: https://codecov.io/gh/rajangare/bookmark-services
      coverageUrl: https://codecov.io/gh/rajangare/bookmark-services
    - name: rabbitmq-advanced-spring-boot-starter
      githubUrl: https://github.com/societe-generale/rabbitmq-advanced-spring-boot-starter
      circleUrl: https://circleci.com/github/societe-generale/rabbitmq-advanced-spring-boot-starter
      codacyUrl: https://app.codacy.com/manual/anandmnair/rabbitmq-advanced-spring-boot-starter/dashboard
      coverageUrl: https://codecov.io/gh/ff4j/ff4j-spring-boot-starter-parent
```

## Have you given admin access to [engineering-stream-bot](https://github.com/engineering-stream-bot) ?  

- [x] Yes

> :pushpin: **Note:** [Details about how to submit](https://engineering-stream-hackathon.github.io/challenge/#/?id=how-to-submit)
