### ISSUE TITLE
Pratik Kumar1

### ISSUE THREAD

**Issue by dECRISES** [engineering-stream-hackathon/challenge#22]
## My project details

```yaml
employee:
  name: Pratik Kumar
  githubUsername: dECRISES
project:
  appUrl: https://github.com/dECRISES/bookmark-management-dashboard
  documentationUrl: https://decrises.github.io/bookmark-management-service/#/
  openApiUrl: https://localhost:9090/swagger-ui.html
  monitoringUrl: not yet implemented
  repositories:
    -
      name: bookmark-management-dashboard
      githubUrl: https://github.com/dECRISES/bookmark-management-dashboard
      travisUrl: https://travis-ci.com/github/dECRISES/bookmark-management-dashboard/builds/184833106
      codacyUrl: https://app.codacy.com/manual/dECRISES/bookmark-management-dashboard/dashboard
      coverageUrl: https://codecov.io/gh/dECRISES/bookmark-management-dashboard
    - name: bookmark-management-service
      githubUrl: https://github.com/dECRISES/bookmark-management-service
      travisUrl: https://travis-ci.com/github/dECRISES/bookmark-management-service/builds/185008341
      codacyUrl: 
      coverageUrl: 
```

## Have you given admin access to [engineering-stream-bot](https://github.com/engineering-stream-bot) ?  

- [x] Yes

> :pushpin: **Note:** [Details about how to submit](https://engineering-stream-hackathon.github.io/challenge/#/?id=how-to-submit)
