### ISSUE TITLE
Prabhu MURUGESAN

### ISSUE THREAD

**Issue by pmurugesan15** [engineering-stream-hackathon/challenge#23]
## My project details

```yaml
employee:
  name: Prabhu MURUGESAN
  githubUsername: pmurugesan15
project:
  appUrl: https://manage-bookmark-ui.herokuapp.com/
  documentationUrl: https://github.com/agil-mugil/engineering-stream-documents
  openApiUrl: https://managebookmark.herokuapp.com/swagger-ui.html
  monitoringUrl: Not Implemented
  repositories:
    -
      name: bookmark
      githubUrl: https://github.com/agil-mugil/bookmark
      travisUrl: https://travis-ci.com/github/agil-mugil/bookmark
      codacyUrl: https://app.codacy.com/gh/agil-mugil/bookmark/dashboard
      coverageUrl: https://codecov.io/gh/agil-mugil/bookmark
    - name: bookmark-ui
      githubUrl: https://github.com/agil-mugil/bookmark-ui
      circleUrl: Not Implemented
      codacyUrl: Not Implemented
      coverageUrl: Not Implemented
```

## Have you given admin access to [engineering-stream-bot](https://github.com/engineering-stream-bot) ?  

- [yes ] Yes

> :pushpin: **Note:** [Details about how to submit](https://engineering-stream-hackathon.github.io/challenge/#/?id=how-to-submit)
