### ISSUE TITLE
Nitin KUMAR 

### ISSUE THREAD

**Issue by phoenixnitin** [engineering-stream-hackathon/challenge#24]
## My project details

```yaml
employee:
  name: Nitin KUMAR
  githubUsername: phoenixnitin
project:
  appUrl: http://www.n4nit.in/
  documentationUrl: https://sg-engr-stream.github.io/frontend-angular/
  openApiUrl: https://short-url-prod.herokuapp.com/api/docs/
  monitoringUrl: https://short-url-prod.herokuapp.com/dashboard
  repositories:
    -
      name: backend-flask
      githubUrl: https://github.com/sg-engr-stream/backend-flask
      travisUrl: https://travis-ci.com/github/sg-engr-stream/backend-flask
      codacyUrl: https://app.codacy.com/gh/sg-engr-stream/backend-flask/dashboard
      coverageUrl: https://codecov.io/gh/sg-engr-stream/backend-flask
    - name: frontend-angular
      githubUrl: https://github.com/sg-engr-stream/frontend-angular
      circleUrl: https://travis-ci.com/github/sg-engr-stream/frontend-angular
      codacyUrl: https://app.codacy.com/gh/sg-engr-stream/frontend-angular/dashboard
      coverageUrl: https://codecov.io/gh/sg-engr-stream/frontend-angular
```

## Have you given admin access to [engineering-stream-bot](https://github.com/engineering-stream-bot) ?  

- [x] Yes

> :pushpin: **Note:** [Details about how to submit](https://engineering-stream-hackathon.github.io/challenge/#/?id=how-to-submit)
