### ISSUE TITLE
Anushree Uppoor

### ISSUE THREAD

**Issue by anushree9497** [engineering-stream-hackathon/challenge#27]
## My project details

```yaml
employee:
  name: Anushree Uppoor
  githubUsername: paul58914080
project:
  appUrl: https://sg-short-url.herokuapp.com/

  repositories:
    -
      name: url-shortening
      githubUrl: https://github.com/Engineering-Stream-2020/url-shortening

 
```

## Have you given admin access to [engineering-stream-bot](https://github.com/engineering-stream-bot) ?  

- [x] Yes

> :pushpin: **Note:** [Details about how to submit](https://engineering-stream-hackathon.github.io/challenge/#/?id=how-to-submit)
