### ISSUE TITLE
ABHAY SHUKLA

### ISSUE THREAD

**Issue by abhayshukla04** [engineering-stream-hackathon/challenge#29]
## My project details

```yaml
employee:
  name: Abhay SHUKLA
  githubUsername: abhayshukla04
project:
  appUrl: https://digital-org-ui.herokuapp.com/  https://digital-organizations.github.io/digital-org.github.io/
  documentationUrl: https://github.com/digital-organizations/digital-org.github.io
  openApiUrl: https://digital-org.herokuapp.com/swagger-ui/#/
  monitoringUrl: https://604d8e9e397a4a2eb81b1b2c5ee7f96c.eastus2.azure.elastic-cloud.com:9243/app/home#/tutorial/apm
  repositories:
    -
      name: digital-org
      githubUrl: https://github.com/digital-organizations/digital-org
      travisUrl: https://travis-ci.com/github/digital-organizations/digital-org
      codacyUrl: https://app.codacy.com/manual/abhayshukla04/digital-org/dashboard
      coverageUrl: https://codecov.io/gh/abhayshukla04/digital-org
    - name: digital-org-ui
      githubUrl: https://github.com/digital-organizations/digital-org-ui
      travisUrl: https://travis-ci.com/github/digital-organizations/digital-org-ui
      circleUrl: https://travis-ci.com/github/digital-organizations/digital-org-ui
      codacyUrl: https://app.codacy.com/manual/abhayshukla04/digital-org-ui/dashboard
      coverageUrl: https://codecov.io/gh/abhayshukla04/digital-org-ui
```

## Have you given admin access to [engineering-stream-bot](https://github.com/engineering-stream-bot) ?  

- [x] Yes

> :pushpin: **Note:** [Details about how to submit](https://engineering-stream-hackathon.github.io/challenge/#/?id=how-to-submit)
