### ISSUE TITLE
Rhishikesh Akole

### ISSUE THREAD

**Issue by rakole** [engineering-stream-hackathon/challenge#31]
## My project details

```yaml
employee:
  name: Rhishikesh Akole
  githubUsername: rakole
project:
  appUrl: https://bbookmark-5da10.web.app/
  documentationUrl: https://github.com/sg-hackathon2020/tinyurl-cards-api
  openApiUrl: https://beyond-bookmarks-api.herokuapp.com/swagger-ui/index.html#/test-controller
  monitoringUrl: 
  repositories:
    -
      name: tinyurl-cards-api
      githubUrl: https://github.com/sg-hackathon2020/tinyurl-cards-api
      circleUrl: https://app.circleci.com/pipelines/github/sg-hackathon2020/tinyurl-cards-api
      codacyUrl: https://app.codacy.com/gh/sg-hackathon2020/tinyurl-cards-api/dashboard
      coverageUrl: https://codecov.io/gh/sg-hackathon2020/tinyurl-cards-api
    - name: org-bookmarks
      githubUrl: https://github.com/sg-hackathon2020/org-bookmarks
      circleUrl: https://app.circleci.com/pipelines/github/sg-hackathon2020/org-bookmarks
```

## Have you given admin access to [engineering-stream-bot](https://github.com/engineering-stream-bot) ?  

- [Y] Yes

> :pushpin: **Note:** [Details about how to submit](https://engineering-stream-hackathon.github.io/challenge/#/?id=how-to-submit)
