### ISSUE TITLE
Kavana Tadagalale

### ISSUE THREAD

**Issue by kavanat** [engineering-stream-hackathon/challenge#32]
## BookMarkUrl shortner

```yaml
employee:
  name: Kavana Tadagalale
  githubUsername: kavanat
project:
  appUrl: https://bookmark-url-shortner-ui.herokuapp.com/
  openApiUrl: https://bookmark-url-shortner.herokuapp.com/swagger-ui/
 aletrnateUrl: https://kavanat.github.io/bookmark-url-shortner-ui/
  repositories:
    -
      name: bookmark-url-shortner
      githubUrl: https://github.com/SG-GSC-Hackathon/bookmark-url-shortner-ui
      githubUrl: https://github.com/SG-GSC-Hackathon/bookmark-url-shortner
      circleUrl: https://app.circleci.com/pipelines/github/SG-GSC-Hackathon/
      codacyUrl: https://app.codacy.com/gh/SG-GSC-Hackathon
      monitoringUrl: https://1a8d32c2fdff4c91a5d2950d2253c50b.eastus2.azure.elastic-cloud.com:9243

```

## Have you given admin access to [engineering-stream-bot](https://github.com/engineering-stream-bot) ?  

- [ ] Yes

> :pushpin: **Note:** [Details about how to submit](https://engineering-stream-hackathon.github.io/challenge/#/?id=how-to-submit)
