### ISSUE TITLE
Shweta Gupta

### ISSUE THREAD

**Issue by shweta1008** [engineering-stream-hackathon/challenge#33]
## SG bookmarks project details

```yaml
employee:
  name: Shweta Gupta
  githubUsername: shweta1008
  emplyeeId: 12159
project:
  appUrl: https://sg-bookmark-webapp.herokuapp.com/
  openApiUrl: https://sg-bookmark.herokuapp.com/swagger-ui/index.html
  monitoringUrl: 
  repositories:
    -
      name: sg-bookmark
      githubUrl: https://github.com/shweta1008/sg_bookmark
      circleCiUrl: https://app.circleci.com/pipelines/github/shweta1008/sg_bookmark
      codacyUrl: https://app.codacy.com/manual/shwetagupta.cdac/sg_bookmark/dashboard
      coverageUrl: 
    - name: sg-bookmark-webapp 
      githubUrl: https://github.com/shweta1008/sg-bookmark-webapp
      circleUrl: https://app.circleci.com/pipelines/github/shweta1008/sg_bookmark
      codacyUrl: https://app.codacy.com/manual/shwetagupta.cdac/sg-bookmark-webapp/dashboard
      coverageUrl: 
	- name: sg-bookmark-webcomponent
	  githubUrl: https://github.com/shweta1008/sg-bookmark-webcomponent
```

## Have you given admin access to [engineering-stream-bot](https://github.com/engineering-stream-bot) ?  

- [x] Yes

> :pushpin: **Note:** [Details about how to submit](https://engineering-stream-hackathon.github.io/challenge/#/?id=how-to-submit)
