### ISSUE TITLE
Prabal SRIVASTAVA

### ISSUE THREAD

**Issue by prabal-es** [engineering-stream-hackathon/challenge#34]
## My project details

```yaml
employee:
  name: Prabal SRIVASTAVA
  githubUsername: prabal-es
project:
  appUrl: https://bookmark-9.herokuapp.com/
  documentationUrl: https://github.com/prabal-es/bookmark-service/blob/master/README.md
  openApiUrl: https://bookmark-service-9.herokuapp.com/api/v1/swagger-ui.html
  monitoringUrl: 
  repositories:
    -
      name: bookmark-service
      githubUrl: https://github.com/prabal-es/bookmark-service
      circleUrl: https://app.circleci.com/pipelines/github/prabal-es/bookmark-service
      codacyUrl: https://app.codacy.com/manual/prabal-es/bookmark-service/dashboard
      coverageUrl: https://codecov.io/gh/prabal-es/bookmark-service
    - name: bookmark-ui
      githubUrl: https://github.com/prabal-es/bookmark-ui
      circleUrl: https://app.circleci.com/pipelines/github/prabal-es/bookmark-ui
      codacyUrl: https://app.codacy.com/manual/prabal-es/bookmark-ui/dashboard
      coverageUrl: https://codecov.io/gh/prabal-es/bookmark-service
```

## Have you given admin access to [engineering-stream-bot](https://github.com/engineering-stream-bot) ?  

- [x] Yes

> :pushpin: **Note:** [Details about how to submit](https://engineering-stream-hackathon.github.io/challenge/#/?id=how-to-submit)
