### ISSUE TITLE
Shakti Kumar

### ISSUE THREAD

**Issue by shakti-aryan** [engineering-stream-hackathon/challenge#35]
## My project details

```yaml
employee:
  name: shakti KUMAR
  githubUsername: shakti-aryan
project:
  appUrl: http://sg-bookmark.appspot.com/
  documentationUrl: https://github.com/shakti-aryan/sg-bookmark/blob/master/README.md
  openApiUrl: http://sg-bookmark.appspot.com/swagger-ui.html
  monitoringUrl: https://console.cloud.google.com/home/dashboard?project=sg-bookmark
  repositories:
    -
      name: sg-bookmark
      githubUrl: https://github.com/shakti-aryan/sg-bookmark
      travisUrl: https://console.cloud.google.com/cloud-build/dashboard?project=sg-bookmark
      codacyUrl: 
      coverageUrl: 
  
```

## Have you given admin access to [engineering-stream-bot](https://github.com/engineering-stream-bot) ?  

- [x] Yes

> :pushpin: **Note:** [Details about how to submit](https://engineering-stream-hackathon.github.io/challenge/#/?id=how-to-submit)
