### ISSUE TITLE
Kannan Sundareshwaran

### ISSUE THREAD

**Issue by SundareshwaranKannan** [engineering-stream-hackathon/challenge#37]
## My project details

```yaml
employee:
  name: KANNAN Sundareshwaran 
  githubUsername: sundareshwaranKannan
project:
  appUrl: https://sundareshwarankannan.github.io/bookmark-ui/
  documentationUrl: 
  openApiUrl: 
  monitoringUrl: 
  repositories:
    -
      name: bookmark-ui
      githubUrl: https://github.com/SundareshwaranKannan/bookmark-ui
      travisUrl: https://travis-ci.com/github/SundareshwaranKannan/bookmark-ui
      codacyUrl: 
      coverageUrl: https://coveralls.io/github/SundareshwaranKannan/bookmark-ui
    - name: bookmark-url-shortener-service
      githubUrl: https://github.com/SundareshwaranKannan/bookmark-url-shortener-service
      travisUrl: https://travis-ci.com/github/SundareshwaranKannan/bookmark-url-shortener-service
      codacyUrl: 
      coverageUrl: https://coveralls.io/github/SundareshwaranKannan/bookmark-url-shortener-service
```

## Have you given admin access to [engineering-stream-bot](https://github.com/engineering-stream-bot) ?  

- [x] Yes

> :pushpin: **Note:** [Details about how to submit](https://engineering-stream-hackathon.github.io/challenge/#/?id=how-to-submit)
