### ISSUE TITLE
Jebish Moses

### ISSUE THREAD

**Issue by mosesjebish** [engineering-stream-hackathon/challenge#38]
## My project details

```yaml
employee:
  name: Jebish Moses
  githubUsername: mosesjebish
project:
  appUrl: https://bookmark-manager-ui.web.app/
  documentationUrl: https://mosesjebish-engineering-stream.github.io/mosesjebish.github.io/#/

  Azure Kubernetes Service URLs:
  openApiUrl: http://20.44.213.195:7443/swagger-ui/index.html?configUrl=/v3/api-docs/swagger-config#/
  serviceDiscoveryUrl: http://40.76.145.40:5443/
  config server: http://52.224.22.87:6443/bookmark-manager.yml
  
  repositories:
    
     - name: service-discovery
      githubUrl: https://github.com/mosesjebish-engineering-stream/service-discovery
      circleUrl: https://app.circleci.com/pipelines/github/mosesjebish-engineering-stream/service-discovery
      dockerHub: https://hub.docker.com/repository/docker/mosesjebish/service-discovery

    - name: config-server
      githubUrl: https://github.com/mosesjebish-engineering-stream/config-server
      circleUrl: https://app.circleci.com/pipelines/github/mosesjebish-engineering-stream/config-server
      dockerHub: https://hub.docker.com/repository/docker/mosesjebish/config-server

   - name: bookmark-manager
      githubUrl: https://github.com/mosesjebish-engineering-stream/bookmark-manager
      circleUrl: https://app.circleci.com/pipelines/github/mosesjebish-engineering-stream/bookmark-manager
      dockerHub: https://hub.docker.com/repository/docker/mosesjebish/bookmark-manager
      codeCov: https://codecov.io/gh/mosesjebish-engineering-stream/bookmark-manager
      codacy: https://app.codacy.com/gh/mosesjebish-engineering-stream/bookmark-manager/dashboard

   - name: auth-server
      githubUrl: https://github.com/mosesjebish-engineering-stream/auth-server
      circleUrl: https://app.circleci.com/pipelines/github/mosesjebish-engineering-stream/auth-server
      dockerHub: https://hub.docker.com/repository/docker/mosesjebish/bookmark-manager

    - name: react-bookmark-manager-ui
      githubUrl: https://github.com/mosesjebish-engineering-stream/react-bookmark-manager-ui
      circleUrl: https://app.circleci.com/pipelines/github/mosesjebish-engineering-stream/react-bookmark-manager-ui
```

## Have you given admin access to [engineering-stream-bot](https://github.com/engineering-stream-bot) ?  

- [x] Yes

> :pushpin: **Note:** [Details about how to submit](https://engineering-stream-hackathon.github.io/challenge/#/?id=how-to-submit)
