### ISSUE TITLE
SURYA PRAKASH

### ISSUE THREAD

**Issue by prakash1431** [engineering-stream-hackathon/challenge#39]
## My project details

```yaml
employee:
  name: Surya Prakash
  githubUsername: prakash1431
project:
  appUrl: https://urlcatalogui.herokuapp.com/
  documentationUrl: https://github.com/sprakash1431/UrlCatalog-FrontEnd/blob/master/README.md
  openApiUrl: https://urlcatalogapi.herokuapp.com/weatherforecast
  monitoringUrl: 
  repositories:
    -
      name: urlcatalog-frontend
      githubUrl: https://github.com/sprakash1431/UrlCatalog-FrontEnd/
      travisUrl: https://travis-ci.com/github/sprakash1431/UrlCatalog-FrontEnd
      codacyUrl: https://app.codacy.com/gh/sprakash1431/UrlCatalog-FrontEnd/dashboard
      coverageUrl: https://codecov.io/gh/sprakash1431/UrlCatalog-FrontEnd
    - name: UrlcatalogApi
      githubUrl: https://github.com/sprakash1431/UrlcatalogApi
      travisUrl: https://travis-ci.com/github/sprakash1431/UrlcatalogApi
      codacyUrl: https://app.codacy.com/gh/sprakash1431/UrlcatalogApi/dashboard
      coverageUrl: na
```

## Have you given admin access to [engineering-stream-bot](https://github.com/engineering-stream-bot) ?  

- [Yes] Yes

> :pushpin: **Note:** [Details about how to submit](https://engineering-stream-hackathon.github.io/challenge/#/?id=how-to-submit)
