### ISSUE TITLE
Vinitha Nair

### ISSUE THREAD

**Issue by VinithaVNair** [engineering-stream-hackathon/challenge#40]
## My project details

```yaml
employee:
  name: Vinitha Nair
  githubUsername: VinithaVNair
project:
  appUrl: https://devs-from-matrix.github.io/ff4j-web-console/features
  documentationUrl: https://engineering-stream-hackathon.github.io/challenge/
  openApiUrl: https://ff4j.herokuapp.com/swagger-ui.html
  monitoringUrl: https://cloud.com/kibana
  repositories:
    -
      githubUrl: https://github.com/VinithaVNair/DigitalWorkSpace
      travisUrl: https://travis-ci.com/github/VinithaVNair/DigitalWorkSpace
      codacyUrl: https://app.codacy.com/manual/VinithaVNair/DigitalWorkSpace/dashboard
      coverageUrl: https://codecov.io/gh/ff4j/ff4j-spring-boot-starter-parent
    - Used kafka which has been containerized and pushed to ACR
     ```
Kubernetes cluster ip:
userMicroService 10.0.232.191/8082
tinyUrlMicroService :10.0.251.199/8081
dwsuiMicroService:10.0.116.234/4200
catalogsMicroService:10.0.168.214:8084

## Have you given admin access to [engineering-stream-bot](https://github.com/engineering-stream-bot) ?i have integrated as collaborator   

- [ ] Yes

> :pushpin: **Note:** [Details about how to submit](https://engineering-stream-hackathon.github.io/challenge/#/?id=how-to-submit)
