### ISSUE TITLE
Supriyo Mukherjee

### ISSUE THREAD

**Issue by Supriyo-sm** [engineering-stream-hackathon/challenge#42]
## My project details

```yaml
employee:
  name: Supriyo Mukherjee
  githubUsername: Supriyo-sm
project:
  appUrl: http://sg-tiny-url-catalog.appspot.com/
  documentationUrl: https://github.com/APPLICATION-DEV-ORG/org-tiny-url/blob/master/README.md
  openApiUrl: http://sg-tiny-url-catalog.appspot.com/swagger-ui.html
  monitoringUrl: 
  repositories:
    -
      name: sg-tiny-url-catalog
      githubUrl: https://github.com/APPLICATION-DEV-ORG/org-tiny-url.git
      travisUrl: 
      codacyUrl: 
      coverageUrl: 
    - name: 
      githubUrl: 
      circleUrl: 
      codacyUrl: 
      coverageUrl: 
```

## Have you given admin access to [engineering-stream-bot](https://github.com/engineering-stream-bot) ?  

- [x] Yes

> :pushpin: **Note:** [Details about how to submit](https://engineering-stream-hackathon.github.io/challenge/#/?id=how-to-submit)
