### ISSUE TITLE
PANDITI SIVAGANESH

### ISSUE THREAD

**Issue by ganesh0479** [engineering-stream-hackathon/challenge#44]
## My project details

```yaml
employee:
  name: PANDITI Sivaganesh
  githubUsername: ganesh0479
project:
  appUrl: http://20.40.46.23/
  documentationUrl: https://ganesh0479.github.io/go-tiny-docs/#/
  openApiUrl: http://20.193.251.252/swagger-ui.html
  monitoringUrl: 
  repositories:
    -
      name: go-tiny
      githubUrl: https://github.com/ganesh0479/go-tiny
      travisUrl: https://travis-ci.org/github/ganesh0479/go-tiny
      codacyUrl: https://app.codacy.com/manual/ganesh0479/go-tiny/dashboard
      coverageUrl: https://codecov.io/github/ganesh0479/go-tiny
    - name: go-tiny-app
      githubUrl: https://github.com/ganesh0479/go-tiny-app
      circleUrl: 
      codacyUrl: 
      coverageUrl: 
```

## Have you given admin access to [engineering-stream-bot](https://github.com/engineering-stream-bot) ?  

- [x] Yes

> :pushpin: **Note:** [Details about how to submit](https://engineering-stream-hackathon.github.io/challenge/#/?id=how-to-submit)
