### ISSUE TITLE
LAKSHMIKANTH RAO MOHAN RAO

### ISSUE THREAD

**Issue by lkanthrao** [engineering-stream-hackathon/challenge#45]
## My project details

```yaml
employee:
  name: Lakshmikanth Rao Mohan Rao
  githubUsername: lkanthrao
project:
  appUrl: https://bookmarkaus-web-ui.herokuapp.com/
  documentationUrl: https://github.com/Societe-Generale-Engineering-Stream/hackathon-offline-works-repo
  openApiUrl: https://bookmarkaus-apis.herokuapp.com/swagger-ui.html
  monitoringUrl: https://metrics.librato.com/s/spaces/1224728
  repositories:
    -
      name: bookmarkaus-apis
      githubUrl: https://github.com/Societe-Generale-Engineering-Stream/bookmarkaus-apis
      travisUrl: https://travis-ci.com/github/ff4j/ff4j-spring-boot-starter-parent
      codacyUrl: https://app.codacy.com/gh/ff4j/ff4j-spring-boot-starter-parent/dashboard
      coverageUrl: https://codecov.io/gh/ff4j/ff4j-spring-boot-starter-parent
    - name: bookmarkaus-web-ui
      githubUrl: https://github.com/Societe-Generale-Engineering-Stream/bookmarkaus-web-ui
      circleUrl: https://circleci.com/github/societe-generale/rabbitmq-advanced-spring-boot-starter
      codacyUrl: https://app.codacy.com/manual/anandmnair/rabbitmq-advanced-spring-boot-starter/dashboard
      coverageUrl: https://codecov.io/gh/ff4j/ff4j-spring-boot-starter-parent
```

## Have you given admin access to [engineering-stream-bot](https://github.com/engineering-stream-bot) ?  

- [x] Yes

> :pushpin: **Note:** [Details about how to submit](https://engineering-stream-hackathon.github.io/challenge/#/?id=how-to-submit)
