### ISSUE TITLE
Soubhik Biswas

### ISSUE THREAD

**Issue by soubhik93** [engineering-stream-hackathon/challenge#6]
## My project details

```yaml
employee:
  name: Soubhik Biswas
  githubUsername: soubhik93
project:
  appUrl: https://bookmark-catalogue-web.herokuapp.com/
  documentationUrl: https://enigineering-stream-hackathon.github.io/documentation/#/
  openApiUrl: https://bookmark-catalogue.herokuapp.com/swagger-ui/index.html?url=/v3/api-docs#/ ,  https://user-management-bs.herokuapp.com/swagger-ui/index.html?url=/v3/api-docs#/ 
  repositories:
    -
      name: user-management
      githubUrl: https://github.com/Enigineering-Stream-Hackathon/user-management
      circleUrl: https://app.circleci.com/pipelines/github/Enigineering-Stream-Hackathon/user-management
      codacyUrl: https://app.codacy.com/gh/Enigineering-Stream-Hackathon/user-management/dashboard
      coverageUrl: https://codecov.io/gh/Enigineering-Stream-Hackathon/user-management
   
   - 
      name: bookmark-catalogue
      githubUrl: https://github.com/Enigineering-Stream-Hackathon/bookmark-catalogue
      circleUrl: https://app.circleci.com/pipelines/github/Enigineering-Stream-Hackathon/bookmark-catalogue
      codacyUrl: https://app.codacy.com/gh/Enigineering-Stream-Hackathon/bookmark-catalogue/dashboard
      coverageUrl: https://codecov.io/gh/Enigineering-Stream-Hackathon/bookmark-catalogue

    - 
      name: bookmark-catalogue-web
      githubUrl: https://github.com/Enigineering-Stream-Hackathon/bookmark-catalogue-web
      circleUrl: https://app.circleci.com/pipelines/github/Enigineering-Stream-Hackathon/bookmark-catalogue-web
      codacyUrl: https://app.codacy.com/gh/Enigineering-Stream-Hackathon/bookmark-catalogue-web/dashboard
      coverageUrl: https://codecov.io/gh/Enigineering-Stream-Hackathon/bookmark-catalogue-web
```

## Have you given admin access to [engineering-stream-bot](https://github.com/engineering-stream-bot) ?  

- Yes

> :pushpin: **Note:** [Details about how to submit](https://engineering-stream-hackathon.github.io/challenge/#/?id=how-to-submit)
