### ISSUE TITLE
[FirstName] [LastName] 

### ISSUE THREAD

**Issue by prameetpradhan** [engineering-stream-hackathon/challenge#7]
## My project details

```yaml
employee:
  name: Paul WILLIAMS
  githubUsername: paul58914080
project:
  appUrl: https://devs-from-matrix.github.io/ff4j-web-console/features
  documentationUrl: https://engineering-stream-hackathon.github.io/challenge/
  openApiUrl: https://ff4j.herokuapp.com/swagger-ui.html
  monitoringUrl: https://cloud.com/kibana
  repositories:
    -
      name: ff4j-spring-boot-starter-parent
      githubUrl: https://github.com/ff4j/ff4j-spring-boot-starter-parent
      travisUrl: https://travis-ci.com/github/ff4j/ff4j-spring-boot-starter-parent
      codacyUrl: https://app.codacy.com/gh/ff4j/ff4j-spring-boot-starter-parent/dashboard
      coverageUrl: https://codecov.io/gh/ff4j/ff4j-spring-boot-starter-parent
    - name: rabbitmq-advanced-spring-boot-starter
      githubUrl: https://github.com/societe-generale/rabbitmq-advanced-spring-boot-starter
      circleUrl: https://circleci.com/github/societe-generale/rabbitmq-advanced-spring-boot-starter
      codacyUrl: https://app.codacy.com/manual/anandmnair/rabbitmq-advanced-spring-boot-starter/dashboard
      coverageUrl: https://codecov.io/gh/ff4j/ff4j-spring-boot-starter-parent
```

## Have you given admin access to [engineering-stream-bot](https://github.com/engineering-stream-bot) ?  

- [ ] Yes

> :pushpin: **Note:** [Details about how to submit](https://engineering-stream-hackathon.github.io/challenge/#/?id=how-to-submit)
