### ISSUE TITLE
Prameet Pradhan

### ISSUE THREAD

**Issue by prameetpradhan** [engineering-stream-hackathon/challenge#8]
## My project details

```yaml
employee:
  name: Prameet Pradhan
  githubUsername: prameetpradhan
project:
  appUrl: http://localhost:4200
  documentationUrl: https://github.com/Prameet-Organization/bookmark-shorturl-service/blob/master/README.md
  openApiUrl: http://localhost:8080/swagger-ui.html
  monitoringUrl: 
  repositories:
    -
      name: bookmark-shorturl-client
      githubUrl: https://github.com/Prameet-Organization/bookmark-shorturl-client
      circleci: https://app.circleci.com/pipelines/github/Prameet-Organization/bookmark-shorturl-client
      codacyUrl: https://app.codacy.com/gh/Prameet-Organization/bookmark-shorturl-client/dashboard
      coverageUrl: 
    - name: bookmark-shorturl-service
      githubUrl: https://github.com/Prameet-Organization/bookmark-shorturl-service
      circleUrl: https://app.circleci.com/pipelines/github/Prameet-Organization/bookmark-shorturl-service
      codacyUrl: https://app.codacy.com/gh/Prameet-Organization/bookmark-shorturl-service/dashboard
      coverageUrl: 
```

## Have you given admin access to [engineering-stream-bot](https://github.com/engineering-stream-bot) ?  

- Yes
